Fixed buildLocalCabal by defining temporary $HOME
This fixes build error:

building path(s) ‘/nix/store/c8i7gm134aij9330h77l4sdna635yj0a-foo.nix’
building /nix/store/c8i7gm134aij9330h77l4sdna635yj0a-foo.nix
cabal2nix: /homeless-shelter/.cache: createDirectory: does not exist (No such file or directory)
error: syntax error, unexpected $end, at /nix/store/c8i7gm134aij9330h77l4sdna635yj0a-foo.nix:1:1
(use ‘--show-trace’ to show detailed location information)…